# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 14
        
    # Make sure you put workflow kit action on top of all the steps 
    - name: Collect Workflow Telemetry
      uses: runforesight/foresight-workflow-kit-action@v1
      with:
        api_key: ${{ secrets.FRS_MIG_TOKEN }}
        
    - name: Build and test project with Maven
      run: mvn -B clean install --file pom.xml
      
    - name: Foresight Test Report Uploader
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-result-junit
        path: target/surefire-reports/

    - name: Analyze Test and/or Coverage Results
      uses: runforesight/foresight-test-kit-action@v1
      with:
        api_key: ${{ secrets.FRS_MIG_TOKEN }}
        test_format: JUNIT
        test_framework: JUNIT
        test_path: target/surefire-reports/
        coverage_format: JACOCO/XML
        coverage_path: ./target/site/jacoco/jacoco.xml
        
    - name: Random wait
      # You may pin to the exact commit or the version.
      # uses: m3y/random-wait-action@62e419c7545f204297b3d0f6d6b376e2256e2dfd
      uses: m3y/random-wait-action@v1
      with:
        # Maximum wait time
        max-wait-time: 15 # optional, default is 10
        
    - name: Codecov
      # You may pin to the exact commit or the version.
      # uses: codecov/codecov-action@f32b3a3741e1053eb607407145bc9619351dc93b
      uses: codecov/codecov-action@v2.1.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        file: ./target/site/jacoco/jacoco.xml
